--- #YAML:1.0
name: Posy-Plugin-YamlConfig
version: 0.42
author:
  - Kathryn Andersen
abstract: Posy plugin to read config files in YAML format.
license: perl
requires:
  Posy: 0.95
  YAML: 0.35
build_requires:
  Test::More: 0
provides:
  Posy::Plugin::YamlConfig:
    file: lib/Posy/Plugin/YamlConfig.pm
    version: 0.42
generated_by: Module::Build version 0.261
